url         : "http://darrinholst.github.com"
title       : "darrinholst.com"
email       : "darrinholst@gmail.com"
author      : "Darrin Holst"
description :
baseurl     :
root        : /
source      : .
destination : public

# Social icons
show_social_icons: true
github_username: darrinholst

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
sass:
  compressed: true
