url                          : http://darrinholst.github.com
title                        : "@darrinholst"
subtitle                     : "#blog #ruby #javascript #paleo #lol"
author                       : Darrin Holst
description                  :
date_format                  : "ordinal"
subscribe_rss                : http://feeds.feedburner.com/darrinholst
root                         : /
permalink                    : /blog/:year/:month/:day/:title
source                       : source
destination                  : public
plugins                      : plugins
category_dir                 : blog/categories
markdown                     : rdiscount
highligter                   : 'pygments'
paginate                     : 5
paginate_path                : "blog/page:num"
excerpt_link                 : 'Read on &rarr;'
titlecase                    : false
disqus_short_name            : darrinholst
disqus_show_comment_count    : true
google_analytics_tracking_id : UA-3052115-1

